### ISSUE TITLE
Add the models available at the google sheets doc

### ISSUE THREAD

**Issue by agostini01** [tflite-soc/tensorflow-models#1]
I would like to add the models available here, to this project.

https://docs.google.com/spreadsheets/d/1hKj5pELC33Xu06RcIfO_xf_vCbxc-cftYhTmQ8y_KLo/edit?ts=5dc047cc#gid=0

**Comment by aditipurandare** [comment]
[TF models.xlsx](https://github.com/tflite-soc/tensorflow-models/files/3841867/TF.models.xlsx)
